# Curator decisions after the local vision check. score = fit of the vision description to the brief (1-5).
BRIEF_EDITS = {
 ("U1","masterclass-1"): "Michelangelo, a sheet of studies connected with the Libyan Sibyl, c. 1510–11: a large worked-up leg study beside two small trial sketches of a seated figure — options opened quickly, one carried through in detail.",
 ("U1","masterclass-6"): "A Post-it 'Teamwork Tools' display wall at a 2018 innovation festival: the sticky-note wall sold as a method, shown so students ask what craft the look of 'design thinking' may hide.",
 ("U2","masterclass-4"): "A Six Thinking Hats session board for the black hat ('doubts': what are the risks?), Wikimedia Colombia workshop, 2025: a role tool that stages one mode of thinking at a time.",
 ("U2","lab-2"): "Trance writing produced by the medium 'Margery' (Mina Crandon) in 1927 and reproduced in 1930: script written without stopping to correct, the practice the Surrealists later borrowed as automatic writing.",
 ("U3","analysis-model"): "Theo van Doesburg, a study for Composition (The Cow), c. 1917–18: an intermediate version in which the cow is already reduced to lines and masses — one step of a development whose next version tried to learn something new.",
}
# (unit, slide) -> per-candidate scores {title: (score, note)} and chosen title + alt text
S = {
 ("U1","cover"): ({"File:Leonardo da Vinci - 1860,0616.98, Two studies of the Virgin and Child with a cat and three studies of the Child with a cat.jpg": (5,"several trial poses of mother, child and cat on one sheet"), "File:Leonardo da Vinci, Study for the Madonna of the Cat (verso).jpg": (3,"single group; fewer alternatives visible")},
   "File:Leonardo da Vinci - 1860,0616.98, Two studies of the Virgin and Child with a cat and three studies of the Child with a cat.jpg",
   "Pen-and-ink sheet by Leonardo da Vinci with two studies of the Virgin holding the Christ Child and a cat, and three smaller studies of the Child with the cat, each pose tried differently."),
 ("U1","analysis-model"): ({"File:Beat the Whites with the Red Wedge.jpg": (5,"geometric poster, Cyrillic text legible"), "File:Klinom Krasnym Bej Belych.JPG": (4,"same poster, weaker reproduction")},
   "File:Beat the Whites with the Red Wedge.jpg",
   "El Lissitzky's 1919–20 poster: a sharp red triangle drives into a white circle on a black and white field, with Russian words placed along the shapes."),
 ("U1","masterclass-1"): ({"File:Studies for the Libyan Sibyl (recto); Studies for the Libyan Sibyl and a small Sketch for a Seated Figure (verso) MET DP807402.jpg": (4,"verso: large leg study + two small seated-figure sketches; brief rewritten to match"), "File:Album of Forty-five Figure Studies MET DP102546.jpg": (3,"only one strong study visible on the spread")},
   "File:Studies for the Libyan Sibyl (recto); Studies for the Libyan Sibyl and a small Sketch for a Seated Figure (verso) MET DP807402.jpg",
   "Chalk drawing by Michelangelo: a large, carefully modelled study of a bent leg and torso, with two small quick sketches of a seated figure in the corners."),
 ("U1","masterclass-2"): ({"File:Schetsen van Hokusai - deel 2 Hokusai manga Katsushika iitsu iboku Hokusai manga nihen (titel op object), RP-P-2004-510.jpg": (1,"actually two book covers (Fuji Hyakkei)"), "File:Hokusai Manga 04.jpg": (2,"one ghost scene, not many varied figures"), "File:Hokusai manga vol.8.jpg": (3,"six framed scenes plus a title page; variety weakly visible")}, None, None),
 ("U1","masterclass-3"): ({"File:GemPaperClipAdvertisementJan1893.png": (4,"paper-clip drawing + 1893 advert text"), "File:Büroklammern -- 2021 -- 6481.jpg": (4,"pile of modern clips; no period"), "File:Paperclip 1900.jpg": (3,"Niagara clip, not Gem")},
   "File:GemPaperClipAdvertisementJan1893.png",
   "An 1893 newspaper advertisement for the Gem paper clip: a large line drawing of the double-loop wire clip beside text praising it for holding papers together."),
 ("U1","masterclass-4"): ({"File:Auguste Rodin - The Thinker - 1917.42 - Cleveland Museum of Art.tif": (4,"bronze seated figure, chin on hand")},
   "File:Auguste Rodin - The Thinker - 1917.42 - Cleveland Museum of Art.tif",
   "Rodin's bronze The Thinker: a seated nude man leans forward, chin resting on his hand, absorbed in thought before acting."),
 ("U1","masterclass-5"): ({"File:Pocket set of drawing instruments MET DP232308.jpg": (5,"open case of brass and steel instruments"), "File:Draughtsman's instruments MET 125791.jpg": (4,"black-and-white catalogue photo")},
   "File:Pocket set of drawing instruments MET DP232308.jpg",
   "An open 18th-century pocket case of drawing instruments: dividers, a scale and other brass and steel tools fitted into an open green patterned case."),
 ("U1","masterclass-6"): ({"File:Post-It Notes Wall at the Fast Company Innovation Festival (30772875917).jpg": (4,"branded 'Teamwork Tools' sticky-note wall; brief rewritten to the commercial angle"), "File:Stickies to brainstorm Edit.2014..jpg": (4,"working brainstorm wall; kept for U2")},
   "File:Post-It Notes Wall at the Fast Company Innovation Festival (30772875917).jpg",
   "A promotional wall covered in coloured sticky notes in vertical stripes around a screen reading 'Post-it Teamwork Tools', with product baskets on the counter below."),
 ("U1","lab-1"): ({"File:Marcel Duchamp, 1917, Fountain, photograph by Alfred Stieglitz.jpg": (5,"urinal on plinth, 'R. Mutt 1917' legible"), "File:Duchamp Fountaine.jpg": (5,"same photograph, cropped")},
   "File:Marcel Duchamp, 1917, Fountain, photograph by Alfred Stieglitz.jpg",
   "Alfred Stieglitz's 1917 photograph of Duchamp's Fountain: a white porcelain urinal turned on its back on a plinth, signed 'R. Mutt 1917', with an entry tag hanging from it."),
 ("U1","lab-2"): ({"File:Theo van Doesburg and Kurt Schwitters, Kleine Dada Soirée (Small Dada Evening), 1922, NGA 154076.jpg": (5,"jumbled typography over red diagonals"), "File:1916 Marcel Słodki Cabaret-Voltaire.jpg": (3,"expressionist woodcut; Dada tactic less visible"), "File:Grand opening of the first Dada exhibition, Berlin, 5 June 1920.jpg": (4,"exhibition view; identifiable people")},
   "File:Theo van Doesburg and Kurt Schwitters, Kleine Dada Soirée (Small Dada Evening), 1922, NGA 154076.jpg",
   "The 1922 Kleine Dada Soirée poster: words in German and Dutch, in many sizes, typefaces and directions, jumbled over bold red diagonal stripes."),
 ("U2","cover"): ({"File:Darwin Tree 1837.png": (5,"full notebook page, 'I think' and branching tree"), "File:Darwins first tree.jpg": (4,"cropped, lower contrast")},
   "File:Darwin Tree 1837.png",
   "A page of Charles Darwin's 1837 notebook headed 'I think', with a small branching tree sketch whose lines split, some ending and some reaching the letters A, B, C and D."),
 ("U2","analysis-model"): ({"File:Study for \"A Sunday on La Grande Jatte\" MET DP259921.jpg": (4,"oil study of the riverbank scene"), "File:Georges Seurat - Étude pour \"La Grande Jatte\" (Study for \"La Grande Jatte\") - 1948-7 - Albright–Knox Art Gallery.tiff": (4,"smaller sketch")},
   "File:Study for \"A Sunday on La Grande Jatte\" MET DP259921.jpg",
   "Seurat's 1884 oil study for A Sunday on La Grande Jatte: small strokes of colour build a grassy riverbank with strollers, trees and boats on the water."),
 ("U2","masterclass-1"): ({"File:Sprite Fright-concept art-Victoria 01.png": (5,"16 labelled expression variants of one character")},
   "File:Sprite Fright-concept art-Victoria 01.png",
   "Concept-art sheet from the short film Sprite Fright: sixteen versions of one red-haired character's face, each labelled with a different expression."),
 ("U2","masterclass-2"): ({"File:Atlanticus Folio 132 133.jpg": (2,"modern composite of four photos with labels"), "File:Hokusai Manga 04.jpg": (2,"one scene")}, None, None),
 ("U2","masterclass-3"): ({"File:Stickies to brainstorm Edit.2014..jpg": (4,"wall of handwritten sticky notes in columns"), "File:Brainstorming Customer Feedback (1).jpg": (3,"hands sorting notes on a table")},
   "File:Stickies to brainstorm Edit.2014..jpg",
   "A wall covered with columns of handwritten blue and orange sticky notes from a brainstorming session, each note a separate idea kept without judging."),
 ("U2","masterclass-4"): ({"File:Oblique Strategies deck, PO Box, The Barbican, London, UK.jpg": (3,"box and edition card; no prompt visible"), "File:Sombrero negro (Dudas).jpg": (5,"black-hat board: doubts and risks with sticky notes")},
   "File:Sombrero negro (Dudas).jpg",
   "A workshop board headed 'Sombrero negro (Dudas)' — the black thinking hat — asking 'What are the doubts? What are the risks?', with coloured sticky-note answers below."),
 ("U2","masterclass-5"): ({"File:Pugh Concept Selection.png": (5,"weighted criteria and scores for concepts A–D"), "File:Pugh Matrix Concepts.png": (4,"criteria table, symbols")},
   "File:Pugh Concept Selection.png",
   "A Pugh concept-selection spreadsheet: criteria such as reliability and safety with weights in rows, four design concepts scored in columns, and totals at the bottom."),
 ("U2","masterclass-6"): ({"File:Vincent van Gogh - Self-portrait with bandaged ear (1889, Courtauld Institute).jpg": (5,"bandaged head, Japanese print behind"), "File:Vincent van Gogh - Self portrait with bandaged ear F529.jpg": (4,"pipe version")},
   "File:Vincent van Gogh - Self-portrait with bandaged ear (1889, Courtauld Institute).jpg",
   "Van Gogh's 1889 self-portrait: the painter in a cap and green coat, a white bandage wrapped around his head, with a Japanese print on the wall behind him."),
 ("U2","lab-1"): ({"File:Kodo Sawaki Zazen.jpg": (4,"monk seated in zazen; identifiable face"), "File:Zazen dans le dojo.jpg": (4,"group in rows; people identifiable")},
   "File:Kodo Sawaki Zazen.jpg",
   "Black-and-white photograph of the Zen teacher Kōdō Sawaki seated cross-legged in robes, upright and still, hands resting in his lap in meditation."),
 ("U2","lab-2"): ({"File:Mina Crandon automatic writing.png": (4,"trance-writing sample page with caption"), "File:HélèneSmith martien01.jpg": (3,"invented script; less legible as 'writing without correcting'"), "File:Francis Ward Monck psychograph 2.png": (2,"drawing with spiral text")},
   "File:Mina Crandon automatic writing.png",
   "A book page reproducing a sample of trance writing by the medium 'Margery', dated 17 March 1927, with lines of brush-written characters under a printed caption."),
 ("U3","cover"): ({"File:Gliding flight, Wright Glider, Kitty Hawk, NC. 1902.10459 A.S..jpg": (5,"glider in flight, pilot visible from behind"), "File:1902 Wright Brothers' Glider Tests - GPN-2002-000125.jpg": (4,"men holding glider on sand")},
   "File:Gliding flight, Wright Glider, Kitty Hawk, NC. 1902.10459 A.S..jpg",
   "The Wright brothers' 1902 biplane glider in flight over the Kitty Hawk dunes, its pilot on the lower wing, under a cloudy sky."),
 ("U3","analysis-model"): ({"File:Cow by Theo van Doesburg Museum of Modern Art 25.1969.jpg": (4,"skeletal cow, lines and masses"), "File:Cow by Theo van Doesburg Museum of Modern Art 227.1948.6.jpg": (3,"already fully abstract; cow not readable alone")},
   "File:Cow by Theo van Doesburg Museum of Modern Art 25.1969.jpg",
   "A pencil study by Theo van Doesburg of a cow with its head lowered, drawn in loose lines and blocky masses as the animal starts to become geometric."),
 ("U3","masterclass-1"): ({"File:Maqueta polifunicular.jpg": (5,"Gaudí's hanging string model with weights (checked by eye too)"), "File:Maqueta funicular.jpg": (4,"modern reconstruction; reads as installation"), "File:Paper prototype of website user interface, 2015-04-16.jpg": (3,"hands writing on a form")},
   "File:Maqueta polifunicular.jpg",
   "Early-1900s photograph of Gaudí's hanging model for the Colonia Güell church: strings loaded with small sacks of weight hang from the ceiling, with paper draped over them to show the inverted form."),
 ("U3","masterclass-2"): ({"File:Sketches for the second movement of Symphony no. 7, op. 92, Beethoven, Petter Sketchbook, 1812, musical autograph - Morgan Library & Museum - New York City - DSC06691.jpg": (4,"handwritten sketch staves with trial versions"), "File:Sketches for the first movement of the Fifth Piano Concerto, op. 73, ('Emperor'), Beethoven, from the Grasnick 3 Sketchbook, 1808-1809, musical autograph - Morgan Library & Museum - New York City - DSC06698.jpg": (4,"similar, wrong work for brief")},
   "File:Sketches for the second movement of Symphony no. 7, op. 92, Beethoven, Petter Sketchbook, 1812, musical autograph - Morgan Library & Museum - New York City - DSC06691.jpg",
   "A page from Beethoven's 1812 sketchbook: hurried ink notation across many staves as themes for the Seventh Symphony are tried out."),
 ("U3","masterclass-3"): ({"File:Wright Brothers Wind Tunnel Replica.jpg": (3,"reads as a printing press; idea not legible"), "File:WB Wind Tunnel.jpg": (1,"statue and desk, not the tunnel")}, None, None),
 ("U3","masterclass-4"): ({"File:AGBell Notebook.jpg": (5,"notebook spread with transmitter sketch"), "File:Design for a Flying Machine.jpg": (4,"technical sketch")},
   "File:AGBell Notebook.jpg",
   "Two pages of Alexander Graham Bell's March 1876 laboratory notebook: a simple line sketch of a transmitting and a receiving instrument, with handwritten notes on the experiment."),
 ("U3","masterclass-5"): ({"File:Paul Klee Pädagogisches Skizzenbuch 10.jpg": (4,"'first/second/third case': one form developed three ways")},
   "File:Paul Klee Pädagogisches Skizzenbuch 10.jpg",
   "A spread from Paul Klee's 1925 Pedagogical Sketchbook: simple lines and shapes worked out as a 'first case', 'second case' and 'third case', each a different development."),
 ("U3","masterclass-6"): ({"File:Wright diary.jpg": (5,"handwritten diary page on flight tests"), "File:Thomas Edison in the Chemistry Laboratory writing in his notebook about rubber experiments. (d1857f0fb1de47f0b31dd6ca657964f5).jpg": (4,"man writing in notebook in lab; identifiable")},
   "File:Wright diary.jpg",
   "A page of Orville Wright's diary for 17 December 1903: dense handwriting on lined paper recording that day's series of flight tests."),
 ("U3","lab-1"): ({"File:Design for Three Chairs with Curved Backs (verso- Sketch for a Sideboard) MET DP807145.jpg": (5,"three chair variants in a row")},
   "File:Design for Three Chairs with Curved Backs (verso- Sketch for a Sideboard) MET DP807145.jpg",
   "An early-19th-century watercolour design sheet showing three chairs side by side, each with a differently curved back and patterned seat."),
 ("U3","lab-2"): ({"File:Wright Glider being flown as a kite. -1900 10457 A.S..jpg": (4,"biplane aloft, no pilot visible")},
   "File:Wright Glider being flown as a kite. -1900 10457 A.S..jpg",
   "The Wright brothers' 1900 glider flying unmanned as a tethered kite against a cloudy sky, its two wings and struts clearly visible."),
 ("ML-CPA","cover"): ({"File:Iterative Process Diagram.svg": (4,"cycle of stages with arrows")},
   "File:Iterative Process Diagram.svg",
   "Diagram of an iterative cycle: planning, requirements, analysis and design, implementation, testing and evaluation, looping back before deployment."),
 ("ML-CPA","analysis-model"): ({"File:Standard Symbols for Process Charts (1), 1921.jpg": (4,"symbol list with labels")},
   "File:Standard Symbols for Process Charts (1), 1921.jpg",
   "A 1921 page of standard process-chart symbols by Frank and Lillian Gilbreth: a column of circles, squares and arrows, each labelled with the step it records."),
 ("ML-CPA","masterclass-1"): ({"File:Process Chart for Ordering Blank Forms - Present Method, 1921.jpg": (5,"step-by-step chart with labelled actions")},
   "File:Process Chart for Ordering Blank Forms - Present Method, 1921.jpg",
   "A 1921 Gilbreth process chart of the 'present method' for ordering printed forms: numbered circles and squares run down the page, each labelled with who does what."),
 ("ML-CPA","masterclass-2"): ({"File:A Jacquard loom showing information punchcards, National Museum of Scotland.jpg": (4,"loom with stack of punched cards"), "File:Punch cards industrial loom.jpg": (4,"industrial cards; CC BY-SA 2.0")},
   "File:A Jacquard loom showing information punchcards, National Museum of Scotland.jpg",
   "A wooden Jacquard loom in a museum: warp threads stretched on one side and a long chain of punched cards hanging on the other, the cards carrying the woven pattern."),
 ("ML-CPA","masterclass-3"): ({"File:Album of Forty-five Figure Studies MET DP102546.jpg": (3,"only one strong study visible")}, None, None),
 ("ML-CPA","masterclass-4"): ({"File:Design for Six Chairs with Scarlet Upholstery (verso- Sketch for Sofa) MET DP807166.jpg": (4,"six chair variants, one upholstery")},
   "File:Design for Six Chairs with Scarlet Upholstery (verso- Sketch for Sofa) MET DP807166.jpg",
   "An early-19th-century design sheet with six chairs in two rows, each a different frame and back, all sharing the same scarlet upholstery."),
 ("ML-CPA","masterclass-5"): ({"File:La danse serpentine, Loïe Fuller et ses transformations.jpg": (4,"eight labelled poses of the dancer"), "File:Folies-Bergère, La Loïe Fuller (NYPL b12156457-5226881).tiff": (4,"single poster")},
   "File:La danse serpentine, Loïe Fuller et ses transformations.jpg",
   "A 19th-century print of Loïe Fuller's Serpentine Dance in eight panels: the dancer's swirling silk takes the shape of serpents, a basket, a propeller and butterflies."),
 ("ML-CPA","masterclass-6"): ({"File:Tableau de résultats au test de Binet-Simon.jpg": (4,"table of tasks against children's results"), "File:Test du carré.jpg": (3,"copied squares; Simon d. 1961")},
   "File:Tableau de résultats au test de Binet-Simon.jpg",
   "A printed 1911 table of Binet–Simon test results from two Paris schools: rows of test tasks cross-referenced with the children's scores."),
 ("ML-CPA","lab-1"): ({"File:Proposed Process Chart for First Orders, 1921.jpg": (4,"flowchart with numbered steps")},
   "File:Proposed Process Chart for First Orders, 1921.jpg",
   "A 1921 Gilbreth 'proposed process chart' for first orders: a short vertical flow of numbered steps for preparing a purchase order, each with a line of description."),
 ("ML-CPA","lab-2"): ({"File:Paul Klee Notebook BF 149.jpg": (4,"handwritten notebook page with diagram")},
   "File:Paul Klee Notebook BF 149.jpg",
   "A handwritten page of Paul Klee's 1922 Bauhaus teaching notebook: a diagram of two linked oval areas with arrows, surrounded by notes in German."),
}
