#!/usr/bin/env python3
"""EX7 step 4: build the canonical catalogue and its generated views.

Reads  canonical/techniques.base.yml (hand-authored) + canonical/mapping.json
       (map_records.py output) + docs/_data/references.yml (key check).
Writes in-practice/CANONICAL-TECHNIQUES.yml          (machine record, private)
       in-practice/CANONICAL-TECHNIQUES.md           (generated reading view)
       in-practice/CANONICAL-TECHNIQUES-BY-UNIT.yml  (units-sorted export for the
       12-lesson cascade: U1.1 ... U6.2, two Lab techniques per lesson)

Never edit the three outputs by hand. Usage (from anywhere):
    python3 creativity-techniques-pedagogy/in-practice/canonical/build.py
"""
import json, pathlib, collections, sys
import yaml

HERE = pathlib.Path(__file__).resolve().parent
IP = HERE.parent
ROOT = IP.parent.parent
REFS = ROOT / "docs/_data/references.yml"

UNITS = {
    "U1": "Introduction to creativity and its importance",
    "U2": "Idea generation and selection techniques",
    "U3": "Development and solution techniques",
    "U4": "Applying creativity techniques at work",
    "U5": "Creativity and technology",
    "U6": "Creativity and personal development",
}
ORDER = ["id", "name", "family", "mode", "primary_source", "source_locator", "gap_work", "source_status",
         "held_note", "catalogue_records", "steps_basis", "steps", "time_min", "group_size", "materials",
         "units", "evidence", "accessibility"]
STEPS_BASIS = "classroom adaptation in course wording; not quoted from, and not a claim about, the source"


class Dumper(yaml.SafeDumper):
    def increase_indent(self, flow=False, indentless=False):
        return super().increase_indent(flow, False)


def main():
    base = yaml.safe_load(open(HERE / "techniques.base.yml"))["techniques"]
    refs = yaml.safe_load(open(REFS))
    mapping = json.load(open(HERE / "mapping.json"))["mapping"]
    stats = json.load(open(HERE / "mapping-stats.json"))
    per = collections.defaultdict(list)
    names = collections.defaultdict(collections.Counter)
    methods = collections.defaultdict(collections.Counter)
    for urn, v in mapping.items():
        if "technique" in v:
            per[v["technique"]].append(urn)
            names[v["technique"]][v["name"]] += 1
            methods[v["technique"]][v["method"]] += 1
    ids = [t["id"] for t in base]
    unknown = set(per) - set(ids)
    if unknown:
        sys.exit(f"mapping targets unknown ids: {sorted(unknown)}")
    out = []
    for t in base:
        ps = t["primary_source"]
        if ps != "gap" and ps not in refs:
            sys.exit(f"{t['id']}: primary_source {ps} not in references.yml")
        if (ps == "gap") != (t["source_status"] in ("gap", "held")):
            sys.exit(f"{t['id']}: source_status {t['source_status']} inconsistent with primary_source {ps}")
        e = dict(t)
        e["catalogue_records"] = sorted(per.get(t["id"], []))
        e["steps_basis"] = STEPS_BASIS
        out.append({k: e[k] for k in ORDER if k in e})

    header = (
        "# CANONICAL-TECHNIQUES.yml — PHASE-EX7 canonical technique catalogue (PRIVATE; never publish).\n"
        "# GENERATED by in-practice/canonical/build.py from canonical/techniques.base.yml and the\n"
        "# record mapping (canonical/map_records.py over runtime/exercises-active.json, read-only).\n"
        "# Do not edit by hand. Field rules: see canonical/techniques.base.yml header.\n"
        "# Lab exercises are chosen from this file (AGENTS.md); only verified primary sources may be\n"
        "# cited to students; gap/held attributions are unverified until procured and page-checked.\n"
        f"# Records: {stats['records_total']} total; {stats['dropped_offtopic']} dropped off-topic; "
        f"{stats['mapped_records']} mapped to {stats['techniques_with_records']} techniques.\n"
    )
    doc = {"schema": "canonical-techniques/v1", "phase": "EX7", "publication_allowed": False,
           "source_snapshot": json.load(open(HERE / "source-snapshot.json")), "techniques": out}
    (IP / "CANONICAL-TECHNIQUES.yml").write_text(header + yaml.dump(doc, Dumper=Dumper, sort_keys=False,
                                                                       allow_unicode=True, width=110))

    # ---------------------------------------------------------------- by unit
    def card(t):
        return {"id": t["id"], "name": t["name"], "family": t["family"], "mode": t["mode"],
                "primary_source": t["primary_source"], "source_status": t["source_status"],
                "time_min": t["time_min"], "embodied": t["family"] == "embodied",
                "catalogue_records": len(t["catalogue_records"])}
    rank = {"verified": 0, "held": 1, "gap": 2}
    by_unit = {}
    for u, title in UNITS.items():
        pool = sorted((t for t in out if u in t["units"]), key=lambda t: (rank[t["source_status"]], t["family"], t["id"]))
        by_unit[u] = {
            "title": title,
            "lessons": [f"{u}.1", f"{u}.2"],
            "divergent_or_both": [t["id"] for t in pool if t["mode"] in ("divergent", "both")],
            "convergent_or_both": [t["id"] for t in pool if t["mode"] in ("convergent", "both")],
            "candidates": [card(t) for t in pool],
        }
    unit_doc = {
        "schema": "canonical-techniques-by-unit/v1", "phase": "EX7", "publication_allowed": False,
        "rule": ("12 lessons (Amendment A9): U1.1 ... U6.2. Each lesson picks two Lab techniques from its unit's "
                 "candidates - recommended one divergent and one convergent (or a 'both' technique). Prefer "
                 "source_status verified; held/gap techniques may run in class but their source may not be cited "
                 "to students until it is in references.yml. Embodied techniques need the opt-out line."),
        "lesson_picks": {f"{u}.{i}": [] for u in UNITS for i in (1, 2)},
        "units": by_unit,
    }
    (IP / "CANONICAL-TECHNIQUES-BY-UNIT.yml").write_text(
        "# GENERATED by in-practice/canonical/build.py — units-sorted export of CANONICAL-TECHNIQUES.yml\n"
        "# for the 12-lesson cascade. PRIVATE; never publish. lesson_picks are left empty on purpose.\n"
        + yaml.dump(unit_doc, Dumper=Dumper, sort_keys=False, allow_unicode=True, width=110))

    # ---------------------------------------------------------------- markdown
    L = ["# Canonical creativity techniques (private reading view)", "",
         "> GENERATED by `canonical/build.py` from `CANONICAL-TECHNIQUES.yml`. Do not edit. Private:",
         "> never publish. Steps are classroom adaptations in course wording, not quotations.",
         "> Only `verified` sources may be cited to students; `held` = in the library but not yet in",
         "> `docs/_data/references.yml`; `gap` = not in the library, attribution unverified.", "",
         f"Records: {stats['records_total']} in `runtime/exercises-active.json`; {stats['dropped_offtopic']} dropped as "
         f"off-topic; {stats['mapped_records']} mapped to {stats['techniques_with_records']} of {len(out)} techniques "
         f"({stats['duplicates_collapsed']} duplicate records collapsed); {stats['unmapped_on_topic']} on-topic "
         "records left unmapped (not a canonical technique, or too vague).", "",
         "## Summary", "",
         "| id | name | family | mode | source | status | records | units |",
         "| --- | --- | --- | --- | --- | --- | ---: | --- |"]
    for t in out:
        L.append(f"| `{t['id']}` | {t['name']} | {t['family']} | {t['mode']} | {t['primary_source']} | "
                 f"{t['source_status']} | {len(t['catalogue_records'])} | {', '.join(t['units'])} |")
    L += ["", "## By unit (for the 12-lesson cascade)", "",
          "Each lesson (U1.1 … U6.2) picks two Lab techniques from its unit, recommended one divergent and one "
          "convergent. Machine export: `CANONICAL-TECHNIQUES-BY-UNIT.yml`.", ""]
    for u, d in by_unit.items():
        L += [f"### {u} — {d['title']}", ""]
        for c in d["candidates"]:
            L.append(f"- `{c['id']}` {c['name']} — {c['family']}, {c['mode']}, {c['source_status']}"
                     f" ({c['primary_source']}), {c['time_min']} min")
        L.append("")
    L += ["## Techniques", ""]
    for t in out:
        L += [f"### {t['name']}", "",
              f"`{t['id']}` · {t['family']} · {t['mode']} · units {', '.join(t['units'])}", "",
              f"- **Source:** {t['primary_source']}"
              + (f" — {t['source_locator']}" if t.get("source_locator") else "")
              + (f" — gap work: {t['gap_work']}" if t.get("gap_work") else "")
              + f" ({t['source_status']})",
              *( [f"- **Library note:** {t['held_note']}"] if t.get("held_note") else [] ),
              f"- **Time:** {t['time_min']} min · **Group:** {t['group_size']} · "
              f"**Materials:** {', '.join(map(str, t['materials']))}",
              f"- **Evidence:** {t['evidence']}",
              f"- **Accessibility:** {t.get('accessibility', '')}",
              f"- **Catalogue records:** {len(t['catalogue_records'])}"
              + (" — labels: " + "; ".join(f"{n} ×{k}" for n, k in names[t['id']].most_common(5))
                 + " · methods: " + ", ".join(f"{m} {k}" for m, k in methods[t['id']].items())
                 if t["catalogue_records"] else " (none: finding for the IP cascade)"),
              "", "Steps (classroom adaptation):", ""]
        L += [f"{i}. {s}" for i, s in enumerate(t["steps"], 1)]
        L.append("")
    (IP / "CANONICAL-TECHNIQUES.md").write_text("\n".join(L))
    print(f"{len(out)} techniques; {sum(len(t['catalogue_records']) for t in out)} records attached")
    for u, d in by_unit.items():
        print(u, len(d["candidates"]), "candidates;", len(d["divergent_or_both"]), "div/both;",
              len(d["convergent_or_both"]), "conv/both;",
              sum(1 for c in d["candidates"] if c["source_status"] == "verified"), "verified")


if __name__ == "__main__":
    main()
